### ISSUE TITLE
Harbor  configuration preheating, error reported "500 Internal Server Error {"message":"READONLY You can't write against a read only replica."}"

### ISSUE THREAD

**Issue by monkey-19890212** [dragonflyoss/helm-charts#295]
### Bug report:
P2P provider is health; Error reported when performing preheating operation
![image](https://github.com/dragonflyoss/helm-charts/assets/52847925/7816e773-d4d7-4bb7-815c-4bdc43fdb03a)

### Environment:

- Dragonfly version: CHART VERSIONS 1.1.67
- OS: ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux harbor.xnwl.com 5.4.0-171-generic #189-Ubuntu SMP Fri Jan 5 14:23:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Others: containerd containerd.io 1.6.33 d2d58213f83a351ca8f528a95fbd145f5654e957

**Comment by monkey-19890212** [comment]
harbor log
![Uploading image.png…]()

**Comment by monkey-19890212** [comment]
habor log
![image](https://github.com/dragonflyoss/helm-charts/assets/52847925/df7de2b8-19b8-4627-8a03-220b28a17629)

**Comment by monkey-19890212** [comment]
Normal after replacing Dragonfly version: CHART VERSIONS 1.1.66

**Comment by gaius-qi** [comment]
@monkey-19890212 You can try the latest version of the charts.
