### ISSUE TITLE
Add support for resource specifications on initContainers

### ISSUE THREAD

**Issue by benhempelmann** [dragonflyoss/helm-charts#296]
### Feature request:

I would like to able to specify resource requests for initContainers via the values.yaml file. I'm working with a platform that requires resource limits/request to be specified for all containers.

### Use case:

For systems that require resource requests/limits on all containers, providing functionality to do this from the values.yaml would significantly increase quality of life and upgradeability. To get around this right now I have to locally modify each initContainer in the templates and if I want to update the helm chart version I have to manually update everything again. This has the potential to lead to mistakes and makes the project more difficult to maintain.

**Comment by gaius-qi** [comment]
@benhempelmann You can try the latest version of the charts.
