### ISSUE TITLE
Redis slave pod can't be backup if master is unavailable

### ISSUE THREAD

**Issue by likunbyl** [dragonflyoss/helm-charts#36]
I deployed the dragonfly with helm chart version 0.5.26, when redis master is down, all the slave also failed, enter `CrashLoopBackOff` stat:
```
dragonfly-redis-slave-0              0/1     CrashLoopBackOff   7          14m
dragonfly-redis-slave-1              0/1     CrashLoopBackOff   7          15m
```
So, if redis slave can't be backup, why we need to deploy redis slave?

Also, I noticed that in the configuration of manager, only redis master is configed:
```      redis:
        password: dragonfly
        host: dragonfly-redis-master.dragonfly.svc.cluster.local
        port: 6379
```
How redis ha work in this situation? does the dragonfly support the redis sentinel ?

**Comment by jim3ma** [comment]
@gaius-qi Can you verify this issue ?

**Comment by gaius-qi** [comment]
If you want to configure redis, refer to [redis charts configuration parameters](https://github.com/bitnami/charts/tree/master/bitnami/redis).
