### ISSUE TITLE
Feature: values.yaml add extraInitContainers configuration

### ISSUE THREAD

**Issue by anjia0532** [dragonflyoss/helm-charts#59]
Like https://github.com/elastic/helm-charts/blob/main/elasticsearch/values.yaml#L160-L163

1. Reduced maintenance / 降低维护工作量 (<https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml#L294-L410>)
2. Easy to custom / 易于定制化

**Comment by anjia0532** [comment]
ping @jim3ma @gaius-qi

**Comment by anjia0532** [comment]
如果认可，我将提交PR

**Comment by jim3ma** [comment]
LGTM
